/**
 * Minimal NOVA native runtime, written directly in LLVM IR.
 *
 * Design decision (documented in docs/M5_NATIVE_BACKEND.md):
 *  - The runtime is *native*: it compiles to real machine code via `llc` and is
 *    linked into the final PE executable. It never touches Node.js / JS.
 *  - It is written in LLVM IR rather than C because in this milestone there is
 *    no guaranteed C compiler in the toolchain (LLVM is the toolchain we target).
 *    The IR is the canonical output of our backend anyway, so the runtime stays
 *    in the same representation and keeps the build free of a C compiler.
 *  - It calls only the Windows API (kernel32): GetStdHandle/WriteFile for
 *    stdout/stderr, GetProcessHeap/HeapAlloc for array data, ExitProcess for
 *    panics. This keeps the executable free of CRT dependencies and lets lld
 *    link it with just the Windows SDK import libraries.
 *
 * Supported runtime surface for M5:
 *   nova_println(i8*, i64)         — print UTF-8 bytes + '\n'
 *   nova_print(i8*, i64)           — print UTF-8 bytes
 *   nova_println_nl()              — print just '\n'  (println() with no args)
 *   nova_panic(i8*, i64)           — write to stderr + exit(1)
 *   nova_array_new(i64 elemsize, i64 count) -> i8*   (heap header + elems)
 *   nova_array_get(i8* hdr, i64 idx, i64 len, i64 elemsize) -> i8*
 *
 * Array value representation (matches M4 ABI "fat pointer"): the *value* is
 * `{ i8*, i64 }` (header pointer + element count). The header on the heap is:
 *   [0..8)  i64 capacity (elements)
 *   [8..)   element bytes
 */

export interface RuntimeIr {
  externs: string[];
  globals: string[];
  funcs: string[];
}

export function runtimeIr(): RuntimeIr {
  const externs = [
    '; --- Windows API (kernel32) ---',
    'declare i8* @GetStdHandle(i32)',
    'declare i8* @GetProcessHeap()',
    'declare i8* @HeapAlloc(i8*, i32, i64)',
    'declare i32 @HeapFree(i8*, i32, i8*)',
    'declare i32 @ReadFile(i8*, i8*, i32, i32*, i8*)',
    'declare i32 @WriteFile(i8*, i8*, i32, i32*, i8*)',
    'declare void @ExitProcess(i32)',
    '; --- Windows API: time / process environment ---',
    'declare i32 @QueryPerformanceCounter(i64*)',
    'declare i32 @QueryPerformanceFrequency(i64*)',
    'declare void @Sleep(i32)',
    'declare i32 @MultiByteToWideChar(i32, i32, i8*, i32, i8*, i32)',
    'declare i32 @WideCharToMultiByte(i32, i32, i8*, i32, i8*, i32, i8*, i8*)',
    'declare i32 @GetEnvironmentVariableW(i8*, i8*, i32)',
    'declare i8* @GetCommandLineW()',
    'declare i8* @CommandLineToArgvW(i8*, i8*)',
    '; --- Windows API: filesystem (kernel32) ---',
    'declare i8* @CreateFileW(i8*, i32, i32, i8*, i32, i32, i8*)',
    'declare i32 @CloseHandle(i8*)',
    'declare i32 @DeleteFileW(i8*)',
    'declare i32 @GetFileAttributesW(i8*)',
    'declare i32 @GetFileSize(i8*, i8*)',
    '; --- Map runtime ---',
    'declare { i8*, i64 } @nova_map_new(i64)',
    'declare i8 @nova_map_set({ i8*, i64 }, i8*, i64, i8*, i64)',
    'declare i8 @nova_map_remove({ i8*, i64 }, i8*, i64)',
    'declare { i8*, i64 } @nova_map_get({ i8*, i64 }, i8*, i64)',
    'declare i8 @nova_map_contains({ i8*, i64 }, i8*, i64)',
    'declare i64 @nova_map_len({ i8*, i64 })',
    'declare void @nova_map_clear({ i8*, i64 })',
    'declare void @nova_map_free({ i8*, i64 })',
    'declare void @nova_map_destroy({ i8*, i64 })',
    'declare { i8*, i64 } @nova_map_iterator_new({ i8*, i64 })',
    'declare { i8*, i64 } @nova_map_iterator_next({ i8*, i64 }, i8*)',
    'declare void @nova_map_iterator_free({ i8*, i64 })',
    'declare i8 @nova_strings_match(i8*, i64, i8*, i64)',
    '; --- LLVM numeric intrinsics ---',
    'declare double @llvm.fabs.f64(double)',
    'declare double @llvm.sqrt.f64(double)',
    'declare double @llvm.pow.f64(double, double)',
    'declare double @llvm.floor.f64(double)',
    'declare double @llvm.ceil.f64(double)',
    'declare double @llvm.round.f64(double)',
  ];

  const globals = [
    '@.nl = private constant [1 x i8] c"\\0A"',
    '@.true = private constant [4 x i8] c"true"',
    '@.false = private constant [5 x i8] c"false"',
    '@.none = private constant [4 x i8] c"None"',
    '@.dot = private constant [1 x i8] c"."',
    '@.minus = private constant [1 x i8] c"-"',
    '@_fltused = global i32 0',
    '@.msg_oob = private constant [18 x i8] c"index out of range"',
  ];

  const funcs = [
    '; --- runtime: io ------------------------------------------------',
    'define { i8*, i64 } @nova_input() {',
    'entry:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %buf = call i8* @HeapAlloc(i8* %heap, i32 0, i64 4096)',
    '  %count_ptr = alloca i32',
    '  %handle = call i8* @GetStdHandle(i32 -10)',
    '  %read_ok = call i32 @ReadFile(i8* %handle, i8* %buf, i32 4095, i32* %count_ptr, i8* null)',
    '  %count32 = load i32, i32* %count_ptr',
    '  %count = zext i32 %count32 to i64',
    '  %empty = icmp eq i64 %count, 0',
    '  br i1 %empty, label %done_empty, label %scan',
    'done_empty:',
    '  br label %done',
    'scan:',
    '  br label %scan_loop',
    'scan_loop:',
    '  %index = phi i64 [ 0, %scan ], [ %next, %scan_loop ]',
    '  %ptr = getelementptr i8, i8* %buf, i64 %index',
    '  %byte = load i8, i8* %ptr',
    '  %is_lf = icmp eq i8 %byte, 10',
    '  %is_cr = icmp eq i8 %byte, 13',
    '  %is_end = or i1 %is_lf, %is_cr',
    '  %not_end = xor i1 %is_end, true',
    '  %next = add i64 %index, 1',
    '  %in_range = icmp ult i64 %next, %count',
    '  %keep_scanning = and i1 %in_range, %not_end',
    '  br i1 %keep_scanning, label %scan_loop, label %done_scan',
    'done_scan:',
    '  %scan_length = select i1 %is_end, i64 %index, i64 %count',
    '  br label %done',
    'done:',
    '  %length = phi i64 [ 0, %done_empty ], [ %scan_length, %done_scan ]',
    '  %s0 = insertvalue { i8*, i64 } undef, i8* %buf, 0',
    '  %s1 = insertvalue { i8*, i64 } %s0, i64 %length, 1',
    '  ret { i8*, i64 } %s1',
    '}',
    '',
    'define void @nova_print(i8* %s, i64 %len) {',
    'entry:',
    '  %h = call i8* @GetStdHandle(i32 -11)',
    '  %wr = alloca i32',
    '  %len32 = trunc i64 %len to i32',
    '  call i32 @WriteFile(i8* %h, i8* %s, i32 %len32, i32* %wr, i8* null)',
    '  ret void',
    '}',
    '',
    'define void @nova_println(i8* %s, i64 %len) {',
    'entry:',
    '  %h = call i8* @GetStdHandle(i32 -11)',
    '  %wr = alloca i32',
    '  %len32 = trunc i64 %len to i32',
    '  call i32 @WriteFile(i8* %h, i8* %s, i32 %len32, i32* %wr, i8* null)',
    '  %nl = getelementptr [1 x i8], [1 x i8]* @.nl, i64 0, i64 0',
    '  call i32 @WriteFile(i8* %h, i8* %nl, i32 1, i32* %wr, i8* null)',
    '  ret void',
    '}',
    '',
    'define void @nova_println_nl() {',
    'entry:',
    '  %h = call i8* @GetStdHandle(i32 -11)',
    '  %wr = alloca i32',
    '  %nl = getelementptr [1 x i8], [1 x i8]* @.nl, i64 0, i64 0',
    '  call i32 @WriteFile(i8* %h, i8* %nl, i32 1, i32* %wr, i8* null)',
    '  ret void',
    '}',
    '',
    '; Signed integer formatting uses a heap buffer and an SSA division loop.',
    'define void @nova_print_int(i64 %value) {',
    'entry:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %buf = call i8* @HeapAlloc(i8* %heap, i32 0, i64 32)',
    '  %negative = icmp slt i64 %value, 0',
    '  %negated = sub i64 0, %value',
    '  %magnitude = select i1 %negative, i64 %negated, i64 %value',
    '  br label %digits',
    'digits:',
    '  %current = phi i64 [ %magnitude, %entry ], [ %quotient, %digits ]',
    '  %index = phi i64 [ 32, %entry ], [ %next_index, %digits ]',
    '  %remainder = urem i64 %current, 10',
    '  %digit = trunc i64 %remainder to i8',
    '  %ascii = add i8 %digit, 48',
    '  %next_index = sub i64 %index, 1',
    '  %digit_ptr = getelementptr i8, i8* %buf, i64 %next_index',
    '  store i8 %ascii, i8* %digit_ptr',
    '  %quotient = udiv i64 %current, 10',
    '  %finished = icmp eq i64 %quotient, 0',
    '  br i1 %finished, label %sign, label %digits',
    'sign:',
    '  br i1 %negative, label %write_sign, label %write',
    'write_sign:',
    '  %sign_next = sub i64 %next_index, 1',
    '  %sign_ptr = getelementptr i8, i8* %buf, i64 %sign_next',
    '  store i8 45, i8* %sign_ptr',
    '  br label %write',
    'write:',
    '  %start = phi i64 [ %next_index, %sign ], [ %sign_next, %write_sign ]',
    '  %length = sub i64 32, %start',
    '  %start_ptr = getelementptr i8, i8* %buf, i64 %start',
    '  %handle = call i8* @GetStdHandle(i32 -11)',
    '  %length32 = trunc i64 %length to i32',
    '  call i32 @WriteFile(i8* %handle, i8* %start_ptr, i32 %length32, i32* null, i8* null)',
    '  call i32 @HeapFree(i8* %heap, i32 0, i8* %buf)',
    '  ret void',
    '}',
    '',
    'define void @nova_println_int(i64 %value) {',
    'entry:',
    '  call void @nova_print_int(i64 %value)',
    '  call void @nova_println_nl()',
    '  ret void',
    '}',
    '',
    'define void @nova_print_bool(i8 %value) {',
    'entry:',
    '  %is_true = icmp ne i8 %value, 0',
    '  br i1 %is_true, label %true_value, label %false_value',
    'true_value:',
    '  %true_ptr = getelementptr [4 x i8], [4 x i8]* @.true, i64 0, i64 0',
    '  call void @nova_print(i8* %true_ptr, i64 4)',
    '  ret void',
    'false_value:',
    '  %false_ptr = getelementptr [5 x i8], [5 x i8]* @.false, i64 0, i64 0',
    '  call void @nova_print(i8* %false_ptr, i64 5)',
    '  ret void',
    '}',
    '',
    'define void @nova_println_bool(i8 %value) {',
    'entry:',
    '  call void @nova_print_bool(i8 %value)',
    '  call void @nova_println_nl()',
    '  ret void',
    '}',
    '',
    '; Fixed six-digit decimal Float formatting without CRT.',
    'define void @nova_print_frac6(i64 %value) {',
    'entry:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %buf = call i8* @HeapAlloc(i8* %heap, i32 0, i64 6)',
    '  br label %digits',
    'digits:',
    '  %current = phi i64 [ %value, %entry ], [ %quotient, %digits ]',
    '  %index = phi i64 [ 6, %entry ], [ %next_index, %digits ]',
    '  %remainder = urem i64 %current, 10',
    '  %digit = trunc i64 %remainder to i8',
    '  %ascii = add i8 %digit, 48',
    '  %next_index = sub i64 %index, 1',
    '  %digit_ptr = getelementptr i8, i8* %buf, i64 %next_index',
    '  store i8 %ascii, i8* %digit_ptr',
    '  %quotient = udiv i64 %current, 10',
    '  %finished = icmp eq i64 %next_index, 0',
    '  br i1 %finished, label %write, label %digits',
    'write:',
    '  call void @nova_print(i8* %buf, i64 6)',
    '  call i32 @HeapFree(i8* %heap, i32 0, i8* %buf)',
    '  ret void',
    '}',
    '',
    'define void @nova_print_float(double %value) {',
    'entry:',
    '  %negative = fcmp olt double %value, 0.0',
    '  %negated = fsub double 0.0, %value',
    '  %magnitude = select i1 %negative, double %negated, double %value',
    '  br i1 %negative, label %write_sign, label %whole',
    'write_sign:',
    '  %minus = getelementptr [1 x i8], [1 x i8]* @.minus, i64 0, i64 0',
    '  call void @nova_print(i8* %minus, i64 1)',
    '  br label %whole',
    'whole:',
    '  %whole_value = fptoui double %magnitude to i64',
    '  call void @nova_print_int(i64 %whole_value)',
    '  %dot = getelementptr [1 x i8], [1 x i8]* @.dot, i64 0, i64 0',
    '  call void @nova_print(i8* %dot, i64 1)',
    '  %whole_float = uitofp i64 %whole_value to double',
    '  %fraction = fsub double %magnitude, %whole_float',
    '  %scaled_float = fmul double %fraction, 1000000.0',
    '  %scaled = fptoui double %scaled_float to i64',
    '  call void @nova_print_frac6(i64 %scaled)',
    '  ret void',
    '}',
    '',
    'define void @nova_println_float(double %value) {',
    'entry:',
    '  call void @nova_print_float(double %value)',
    '  call void @nova_println_nl()',
    '  ret void',
    '}',
    '',
    '; Option<String> printing: prints "None" or the string content.',
    'define void @nova_print_option_string({ i8*, i64 } %value) {',
    'entry:',
    '  %ptr = extractvalue { i8*, i64 } %value, 0',
    '  %is_null = icmp eq i8* %ptr, null',
    '  br i1 %is_null, label %none, label %some',
    'none:',
    '  %none_ptr = getelementptr [4 x i8], [4 x i8]* @.none, i64 0, i64 0',
    '  call void @nova_print(i8* %none_ptr, i64 4)',
    '  ret void',
    'some:',
    '  %len = extractvalue { i8*, i64 } %value, 1',
    '  call void @nova_print(i8* %ptr, i64 %len)',
    '  ret void',
    '}',
    '',
    'define void @nova_println_option_string({ i8*, i64 } %value) {',
    'entry:',
    '  call void @nova_print_option_string({ i8*, i64 } %value)',
    '  call void @nova_println_nl()',
    '  ret void',
    '}',
    '',
    'define void @nova_panic(i8* %msg, i64 %len) {',
    'entry:',
    '  %h = call i8* @GetStdHandle(i32 -12)',
    '  %wr = alloca i32',
    '  %len32 = trunc i64 %len to i32',
    '  call i32 @WriteFile(i8* %h, i8* %msg, i32 %len32, i32* %wr, i8* null)',
    '  call void @ExitProcess(i32 1)',
    '  unreachable',
    '}',
    '',
    '; --- runtime: time / environment / process arguments --------------',
    '; Monotonic-style high-resolution clock in milliseconds.',
    'define i64 @nova_clock_ms() {',
    'entry:',
    '  %counter = alloca i64',
    '  %freq = alloca i64',
    '  call i32 @QueryPerformanceCounter(i64* %counter)',
    '  call i32 @QueryPerformanceFrequency(i64* %freq)',
    '  %c = load i64, i64* %counter',
    '  %f = load i64, i64* %freq',
    '  %bad_freq = icmp ule i64 %f, 0',
    '  %f_safe = select i1 %bad_freq, i64 1, i64 %f',
    '  %scaled = mul i64 %c, 1000',
    '  %ms = udiv i64 %scaled, %f_safe',
    '  ret i64 %ms',
    '}',
    '',
    'define void @nova_sleep_ms(i64 %ms) {',
    'entry:',
    '  %ms32 = trunc i64 %ms to i32',
    '  call void @Sleep(i32 %ms32)',
    '  ret void',
    '}',
    '',
    '; Convert a UTF-8 slice into a NUL-terminated UTF-16 heap buffer.',
    '; Returns null on encoding failure.',
    'define i8* @nova_utf8_to_wide(i8* %utf8, i64 %len) {',
    'entry:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %len32 = trunc i64 %len to i32',
    '  %wlen = call i32 @MultiByteToWideChar(i32 65001, i32 0, i8* %utf8, i32 %len32, i8* null, i32 0)',
    '  %bad = icmp sle i32 %wlen, 0',
    '  br i1 %bad, label %fail, label %alloc',
    'fail:',
    '  ret i8* null',
    'alloc:',
    '  %wchars = sext i32 %wlen to i64',
    '  %bytes = mul i64 %wchars, 2',
    '  %need = add i64 %bytes, 2',
    '  %buf = call i8* @HeapAlloc(i8* %heap, i32 8, i64 %need)',
    '  %is_null = icmp eq i8* %buf, null',
    '  br i1 %is_null, label %fail, label %fill',
    'fill:',
    '  call i32 @MultiByteToWideChar(i32 65001, i32 0, i8* %utf8, i32 %len32, i8* %buf, i32 %wlen)',
    '  %term = getelementptr i8, i8* %buf, i64 %bytes',
    '  %term16 = bitcast i8* %term to i16*',
    '  store i16 0, i16* %term16',
    '  ret i8* %buf',
    '}',
    '',
    '; Convert a NUL-terminated UTF-16 buffer into a UTF-8 byte slice.',
    '; Returns { null, 0 } on encoding failure.',
    'define { i8*, i64 } @nova_wide_to_utf8(i8* %wide) {',
    'entry:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %ulen = call i32 @WideCharToMultiByte(i32 65001, i32 0, i8* %wide, i32 -1, i8* null, i32 0, i8* null, i8* null)',
    '  %bad = icmp sle i32 %ulen, 0',
    '  br i1 %bad, label %fail, label %alloc',
    'fail:',
    '  %f0 = insertvalue { i8*, i64 } undef, i8* null, 0',
    '  %f1 = insertvalue { i8*, i64 } %f0, i64 0, 1',
    '  ret { i8*, i64 } %f1',
    'alloc:',
    '  %ulen64 = sext i32 %ulen to i64',
    '  %buf = call i8* @HeapAlloc(i8* %heap, i32 8, i64 %ulen64)',
    '  %is_null = icmp eq i8* %buf, null',
    '  br i1 %is_null, label %fail, label %fill',
    'fill:',
    '  %wrote = call i32 @WideCharToMultiByte(i32 65001, i32 0, i8* %wide, i32 -1, i8* %buf, i32 %ulen, i8* null, i8* null)',
    '  %wrote64 = sext i32 %wrote to i64',
    '  %slen = sub i64 %wrote64, 1',
    '  %s0 = insertvalue { i8*, i64 } undef, i8* %buf, 0',
    '  %s1 = insertvalue { i8*, i64 } %s0, i64 %slen, 1',
    '  ret { i8*, i64 } %s1',
    '}',
    '',
    '; Option<String> ABI: { ptr, len } with a null ptr meaning None.',
    'define { i8*, i64 } @nova_env_get(i8* %name, i64 %len) {',
    'entry:',
    '  %wname = call i8* @nova_utf8_to_wide(i8* %name, i64 %len)',
    '  %wnull = icmp eq i8* %wname, null',
    '  br i1 %wnull, label %none, label %query',
    'query:',
    '  %size = call i32 @GetEnvironmentVariableW(i8* %wname, i8* null, i32 0)',
    '  %missing = icmp eq i32 %size, 0',
    '  br i1 %missing, label %none, label %alloc',
    'none:',
    '  %n0 = insertvalue { i8*, i64 } undef, i8* null, 0',
    '  %n1 = insertvalue { i8*, i64 } %n0, i64 0, 1',
    '  ret { i8*, i64 } %n1',
    'alloc:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %wchars = sext i32 %size to i64',
    '  %need = mul i64 %wchars, 2',
    '  %wbuf = call i8* @HeapAlloc(i8* %heap, i32 8, i64 %need)',
    '  %got = call i32 @GetEnvironmentVariableW(i8* %wname, i8* %wbuf, i32 %size)',
    '  %failed = icmp eq i32 %got, 0',
    '  br i1 %failed, label %none, label %conv',
    'conv:',
    '  %val = call { i8*, i64 } @nova_wide_to_utf8(i8* %wbuf)',
    '  ret { i8*, i64 } %val',
    '}',
    '',
    'define i8 @nova_env_has(i8* %name, i64 %len) {',
    'entry:',
    '  %wname = call i8* @nova_utf8_to_wide(i8* %name, i64 %len)',
    '  %wnull = icmp eq i8* %wname, null',
    '  br i1 %wnull, label %no, label %query',
    'query:',
    '  %size = call i32 @GetEnvironmentVariableW(i8* %wname, i8* null, i32 0)',
    '  %exists = icmp ne i32 %size, 0',
    '  %b = zext i1 %exists to i8',
    '  ret i8 %b',
    'no:',
    '  ret i8 0',
    '}',
    '',
    '; Process arguments: Array<String> header (count at [0..8), then N x {i8*,i64}).',
    '; argv[0] (program path) is excluded.',
    'define { i8*, i64 } @nova_args() {',
    'entry:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %cmd = call i8* @GetCommandLineW()',
    '  %argv_slot = alloca i8*',
    '  %argv = call i8* @CommandLineToArgvW(i8* %cmd, i8* %argv_slot)',
    '  %anull = icmp eq i8* %argv, null',
    '  br i1 %anull, label %none, label %count',
    'none:',
    '  %z0 = insertvalue { i8*, i64 } undef, i8* null, 0',
    '  %z1 = insertvalue { i8*, i64 } %z0, i64 0, 1',
    '  ret { i8*, i64 } %z1',
    'count:',
    '  %argc32p = bitcast i8* %argv_slot to i32*',
    '  %argc32 = load i32, i32* %argc32p',
    '  %argc = sext i32 %argc32 to i64',
    '  %raw_count = sub i64 %argc, 1',
    '  %empty = icmp sle i64 %raw_count, 0',
    '  br i1 %empty, label %none, label %alloc',
    'alloc:',
    '  %data = mul i64 %raw_count, 16',
    '  %need = add i64 %data, 8',
    '  %hdr = call i8* @HeapAlloc(i8* %heap, i32 8, i64 %need)',
    '  %hdr64 = bitcast i8* %hdr to i64*',
    '  store i64 %raw_count, i64* %hdr64',
    '  br label %loop',
    'loop:',
    '  %i = phi i64 [ 1, %alloc ], [ %inext, %body ]',
    '  %done = icmp uge i64 %i, %argc',
    '  br i1 %done, label %finish, label %body',
    'body:',
    '  %slot = getelementptr i8*, i8* %argv, i64 %i',
    '  %warg = load i8*, i8** %slot',
    '  %s = call { i8*, i64 } @nova_wide_to_utf8(i8* %warg)',
    '  %j = sub i64 %i, 1',
    '  %off = mul i64 %j, 16',
    '  %eo = add i64 %off, 8',
    '  %ep = getelementptr i8, i8* %hdr, i64 %eo',
    '  %epc = bitcast i8* %ep to { i8*, i64 }*',
    '  store { i8*, i64 } %s, { i8*, i64 }* %epc',
    '  %inext = add i64 %i, 1',
    '  br label %loop',
    'finish:',
    '  %r0 = insertvalue { i8*, i64 } undef, i8* %hdr, 0',
    '  %r1 = insertvalue { i8*, i64 } %r0, i64 %raw_count, 1',
    '  ret { i8*, i64 } %r1',
    '}',
    '',
    '; --- runtime: arrays ----------------------------------------------',
    '; Allocate a heap array of `count` elements of `elemsize` bytes.',
    '; Returns the header pointer; value side is { i8* %hdr, i64 %count }.',
    'define i8* @nova_array_new(i64 %elemsize, i64 %count) {',
    'entry:',
    '  %h = call i8* @GetProcessHeap()',
    '  %data = mul i64 %elemsize, %count',
    '  %need = add i64 %data, 8',
    '  %p = call i8* @HeapAlloc(i8* %h, i32 0, i64 %need)',
    '  %p0 = bitcast i8* %p to i64*',
    '  store i64 %count, i64* %p0',
    '  ret i8* %p',
    '}',
    '',
    '; Bounds-checked element pointer: returns the address of element %idx.',
    'define i8* @nova_array_get(i8* %hdr, i64 %idx, i64 %len, i64 %elemsize) {',
    'entry:',
    '  %inb = icmp ult i64 %idx, %len',
    '  br i1 %inb, label %ok, label %panic',
    'panic:',
    '  %msg = getelementptr [18 x i8], [18 x i8]* @.msg_oob, i64 0, i64 0',
    '  call void @nova_panic(i8* %msg, i64 18)',
    '  unreachable',
    'ok:',
    '  %byte = mul i64 %idx, %elemsize',
    '  %off = add i64 %byte, 8',
    '  %p = getelementptr i8, i8* %hdr, i64 %off',
    '  ret i8* %p',
    '}',
    '',
    '; --- runtime: filesystem -------------------------------------------',
    '; file_exists(path) -> Bool (i8): true when GetFileAttributesW does not',
    '; report INVALID_FILE_ATTRIBUTES (0xFFFFFFFF).',
    'define i8 @nova_file_exists(i8* %path, i64 %len) {',
    'entry:',
    '  %wpath = call i8* @nova_utf8_to_wide(i8* %path, i64 %len)',
    '  %wnull = icmp eq i8* %wpath, null',
    '  br i1 %wnull, label %no, label %query',
    'query:',
    '  %attrs = call i32 @GetFileAttributesW(i8* %wpath)',
    '  %invalid = icmp eq i32 %attrs, -1',
    '  %exists = xor i1 %invalid, true',
    '  %b = zext i1 %exists to i8',
    '  ret i8 %b',
    'no:',
    '  ret i8 0',
    '}',
    '',
    '; file_read(path) -> Result<String, String>',
    '; ABI: { { i8*, i64 } payload, i64 discriminant } with 0 = Ok, 1 = Err.',
    '; Ok  = { heap-allocated file bytes, file size }',
    '; Err = { "", 0 } (message refinement is a documented v2 gap).',
    'define { { i8*, i64 }, i64 } @nova_file_read(i8* %path, i64 %len) {',
    'entry:',
    '  %wpath = call i8* @nova_utf8_to_wide(i8* %path, i64 %len)',
    '  %wnull = icmp eq i8* %wpath, null',
    '  br i1 %wnull, label %error, label %open',
    'open:',
    '  %h = call i8* @CreateFileW(i8* %wpath, i32 2147483648, i32 1, i8* null, i32 0, i32 128, i8* null)',
    '  %invalid = icmp eq i8* %h, inttoptr (i64 -1 to i8*)',
    '  br i1 %invalid, label %error, label %size',
    'size:',
    '  %fsz = call i32 @GetFileSize(i8* %h, i8* null)',
    '  %bad = icmp eq i32 %fsz, -1',
    '  br i1 %bad, label %error_close, label %alloc',
    'error_close:',
    '  call i32 @CloseHandle(i8* %h)',
    '  br label %error',
    'alloc:',
    '  %heap = call i8* @GetProcessHeap()',
    '  %fsz64 = zext i32 %fsz to i64',
    '  %buf = call i8* @HeapAlloc(i8* %heap, i32 0, i64 %fsz64)',
    '  %wr = alloca i32',
    '  call i32 @ReadFile(i8* %h, i8* %buf, i32 %fsz, i32* %wr, i8* null)',
    '  call i32 @CloseHandle(i8* %h)',
    '  %s0 = insertvalue { i8*, i64 } undef, i8* %buf, 0',
    '  %s1 = insertvalue { i8*, i64 } %s0, i64 %fsz64, 1',
    '  %r0 = insertvalue { { i8*, i64 }, i64 } undef, { i8*, i64 } %s1, 0',
    '  %r1 = insertvalue { { i8*, i64 }, i64 } %r0, i64 0, 1',
    '  ret { { i8*, i64 }, i64 } %r1',
    'error:',
    '  %e0 = insertvalue { i8*, i64 } undef, i8* null, 0',
    '  %e1 = insertvalue { i8*, i64 } %e0, i64 0, 1',
    '  %r2 = insertvalue { { i8*, i64 }, i64 } undef, { i8*, i64 } %e1, 0',
    '  %r3 = insertvalue { { i8*, i64 }, i64 } %r2, i64 1, 1',
    '  ret { { i8*, i64 }, i64 } %r3',
    '}',
    '',
    '; file_write(path, data) -> Bool (i8): true on success.',
    '; Creates (or truncates) the file with CREATE_ALWAYS.',
    'define i8 @nova_file_write(i8* %path, i64 %plen, i8* %data, i64 %dlen) {',
    'entry:',
    '  %wpath = call i8* @nova_utf8_to_wide(i8* %path, i64 %plen)',
    '  %wnull = icmp eq i8* %wpath, null',
    '  br i1 %wnull, label %fail, label %open',
    'open:',
    '  %h = call i8* @CreateFileW(i8* %wpath, i32 1073741824, i32 0, i8* null, i32 2, i32 128, i8* null)',
    '  %invalid = icmp eq i8* %h, inttoptr (i64 -1 to i8*)',
    '  br i1 %invalid, label %fail, label %write',
    'write:',
    '  %wr = alloca i32',
    '  %len32 = trunc i64 %dlen to i32',
    '  %ok = call i32 @WriteFile(i8* %h, i8* %data, i32 %len32, i32* %wr, i8* null)',
    '  call i32 @CloseHandle(i8* %h)',
    '  %b = trunc i32 %ok to i8',
    '  ret i8 %b',
    'fail:',
    '  ret i8 0',
    '}',
    '',
    '; file_delete(path) -> Bool (i8): true when DeleteFileW succeeds.',
    'define i8 @nova_file_delete(i8* %path, i64 %len) {',
    'entry:',
    '  %wpath = call i8* @nova_utf8_to_wide(i8* %path, i64 %len)',
    '  %wnull = icmp eq i8* %wpath, null',
    '  br i1 %wnull, label %no, label %del',
    'del:',
    '  %d = call i32 @DeleteFileW(i8* %wpath)',
    '  %is_true = icmp ne i32 %d, 0',
    '  %b = zext i1 %is_true to i8',
    '  ret i8 %b',
    'no:',
    '  ret i8 0',
    '}',
  ];
    '',    

  return { externs, globals, funcs };
}